### ISSUE TITLE
Unexpected error message when updating desktop client on mac os

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2854]
Close application after update notification has been received. Update from 3.82.9 -> 3.82.10

![Screenshot 2021-03-16 at 4 45 53 PM](https://user-images.githubusercontent.com/8296817/111338717-72315d00-8677-11eb-9d3d-d29e7e5961be.png)

Client: darwin
Type: PREMIUM
Tutanota version: 3.82.9
Timestamp (UTC): Tue, 16 Mar 2021 15:18:44 GMT
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop-test/3.82.9 Chrome/87.0.4280.141 Electron/11.3.0 Safari/537.36
TypeError
Error message: e.install is not a function
Stacktrace:
TypeError: e.install is not a function
at /Applications/test Tutanota Desktop.app/Contents/Resources/app.asar/desktop/DesktopMain-cd22e31d.js:13:221583
